// Renders PUBLISHED casts (kind-30023 long-form, whose body is the real
// htmlToMarkdown conversion of capture bodyHtml) through the actual public feed
// + DetailPanel, and asserts the rendered DOM is free of the cast-rendering
// defects reported 2026-07-13: literal "](url)" brace spills, full-width avatar
// images, smashed stat digits, a duplicate hero above inline media.
//
// This is the render half of the coverage: cast-markdown.test.ts (ext) guards
// the markdown STRING; this spec guards how ReactMarkdown draws it. The
// kind-30023 events are generated by the real factory + htmlToMarkdown in
// discerned-ext/tests/nostr/event-fixture-generation.test.ts (the card-* files)
// — run `pnpm test` in discerned-ext to regenerate after a converter change.
//
// Part of the always-on `web` Playwright project (no opt-in env var) so cast
// rendering is covered on every run, unlike the opt-in tweet-cast-photos spec.

import { test, expect, type Page } from '@playwright/test';
import { generateSecretKey, finalizeEvent } from 'nostr-tools/pure';
import type { EventTemplate, NostrEvent } from 'nostr-tools/core';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const EVENTS_ROOT = resolve(__dirname, '..', 'fixtures', 'events');

interface GeneratedEventFixture {
  source: string;
  variant: string;
  capture: { title: string; url: string };
  template: EventTemplate;
}

function loadCardEvent(slug: string): { event: NostrEvent; title: string } {
  const fx = JSON.parse(
    readFileSync(resolve(EVENTS_ROOT, `card-${slug}.kind30023.json`), 'utf8'),
  ) as GeneratedEventFixture;
  const event = finalizeEvent(fx.template, generateSecretKey());
  return { event, title: fx.capture.title };
}

async function mockRelayWith(page: Page, event: NostrEvent): Promise<void> {
  await page.addInitScript(() => {
    try { localStorage.setItem('discerned.relayMode', 'production'); } catch { /* ignore */ }
  });
  await page.routeWebSocket(/^wss:\/\//, (ws) => {
    ws.onMessage((message: string | Buffer) => {
      const msg = typeof message === 'string' ? message : message.toString();
      try {
        const parsed = JSON.parse(msg);
        if (Array.isArray(parsed) && parsed[0] === 'REQ') {
          const subId = parsed[1];
          ws.send(JSON.stringify(['EVENT', subId, event]));
          ws.send(JSON.stringify(['EOSE', subId]));
        }
      } catch { /* ignore non-JSON frames */ }
    });
  });
}

async function openDetail(page: Page, rowText: string) {
  await page.goto('/discerns');
  const row = page.locator('article.clip', { hasText: rowText }).first();
  await row.waitFor({ state: 'visible', timeout: 10_000 });
  await row.click();
  const clipBody = page.locator('.clip-body');
  await clipBody.waitFor({ state: 'visible', timeout: 10_000 });
  await page.waitForTimeout(400);
  return clipBody;
}

// The rendered clip body must never show a literal "](url)" — that is what a
// brace spill (an anchor with block content that broke turndown) looks like on
// screen. ReactMarkdown renders valid links as <a>, so a leftover "](" only
// appears as text when the markdown was malformed.
async function assertNoBraceSpill(clipBody: ReturnType<Page['locator']>) {
  const text = (await clipBody.innerText()) ?? '';
  expect(text, 'rendered clip body contains a literal "](" — markdown brace spill').not.toContain('](');
  expect(text, 'rendered clip body shows a raw image/link opener').not.toMatch(/!\[[^\]]*\]\(/);
}

test.describe('public cast rendering — kind-30023 markdown', () => {
  test('tweet cast: video poster inline, stats separated, no brace spill, no giant avatar', async ({ page }) => {
    const { event, title } = loadCardEvent('tweet-card');
    await mockRelayWith(page, event);
    const clipBody = await openDetail(page, title);

    await assertNoBraceSpill(clipBody);

    // Author name and handle are separated (not "CIA@CIA").
    await expect(clipBody).toContainText('CIA');
    await expect(clipBody).not.toContainText('CIA@CIA');

    // The stat line survives with its glyphs + separators.
    await expect(clipBody).toContainText('1.3K');
    await expect(clipBody).toContainText('43K');
    await expect(clipBody).toContainText('4.1M Views');

    // The video poster renders as an <img>, and it is NOT rendered twice (once
    // as a top hero + once inline). Exactly one poster image.
    const posterImgs = clipBody.locator('img[src*="poster.jpg"]');
    await expect(posterImgs).toHaveCount(1);

    // The 48px avatar must NOT appear as a full-width content image.
    await expect(clipBody.locator('img[src*="avatar.jpg"]')).toHaveCount(0);

    await clipBody.screenshot({ path: resolve(__dirname, '..', '..', 'test-output', 'cast-render-tweet.png') });
  });

  test('primal cast: quote as blockquote, stats separated, no avatars, no brace spill', async ({ page }) => {
    const { event, title } = loadCardEvent('primal-note');
    await mockRelayWith(page, event);
    const clipBody = await openDetail(page, title);

    await assertNoBraceSpill(clipBody);

    // Primary note + embedded quote text both present.
    await expect(clipBody).toContainText('Terrible idea');
    await expect(clipBody).toContainText('Vitor Pamplona');
    await expect(clipBody).toContainText('public wallet');

    // The embedded quote renders inside a <blockquote>.
    await expect(clipBody.locator('blockquote')).toContainText('public wallet');

    // Engagement counts render separated ("8 · 528 · 62"), never glued.
    await expect(clipBody).toContainText('528');
    await expect(clipBody).not.toContainText('852862');

    // A text-only note publishes NO images (avatars dropped).
    await expect(clipBody.locator('img')).toHaveCount(0);

    await clipBody.screenshot({ path: resolve(__dirname, '..', '..', 'test-output', 'cast-render-primal.png') });
  });

  test('article cast: hero image inline (once), no duplicate top hero', async ({ page }) => {
    const { event, title } = loadCardEvent('article-inline-img');
    await mockRelayWith(page, event);
    const clipBody = await openDetail(page, title);

    await assertNoBraceSpill(clipBody);

    await expect(clipBody).toContainText('home server deserves better');
    await expect(clipBody).toContainText('spare-PC reliability');

    // The hero image is present exactly once — the markdown carries it inline,
    // so DetailPanel must NOT also render it as a top hero (that showed the
    // same image twice, in the wrong place first).
    await expect(clipBody.locator('img[src*="hero.jpg"]')).toHaveCount(1);
    // And it sits between the two paragraphs, not above the first.
    const order = await clipBody.evaluate((root) => {
      const out: string[] = [];
      root.querySelectorAll('p, img').forEach((el) => {
        out.push(el.tagName === 'IMG' ? 'IMG' : (el.textContent ?? '').slice(0, 20));
      });
      return out;
    });
    const firstPara = order.findIndex((t) => t.includes('home server'));
    const img = order.indexOf('IMG');
    const secondPara = order.findIndex((t) => t.includes('Treating it'));
    expect(firstPara).toBeGreaterThanOrEqual(0);
    expect(img).toBeGreaterThan(firstPara);
    expect(secondPara).toBeGreaterThan(img);

    await clipBody.screenshot({ path: resolve(__dirname, '..', '..', 'test-output', 'cast-render-article.png') });
  });
});
