// Verifies that the web app's parseEvent() correctly reverses what the
// extension's event factory produces. Cross-package consistency is the whole
// point of these tests — drift here breaks the public feed.
//
// Two layers:
//   1. CURRENT format — event templates generated by the REAL extension
//      factory (discerned-ext/tests/nostr/event-fixture-generation.test.ts →
//      tests/fixtures/events/*.json). Regenerated on every ext `pnpm test`, so
//      factory changes reach this parser test without hand-mirroring.
//   2. LEGACY format — a hand-built template of the pre-snippet era
//      ("Discerned: …" summary line), kept because old casts live forever on
//      relays and must keep parsing.

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { generateSecretKey, finalizeEvent } from 'nostr-tools/pure';
import type { EventTemplate } from 'nostr-tools/core';
import { parseEvent } from '@/lib/nostr/parse';
import { SNIPPET_SENTINEL_OPEN } from '@/lib/nostr/strip-snippet';
import { SIGNAL_LEVELS } from '@/lib/constants';
import type { Capture, Evaluation } from '@/lib/types';

// First content line, mirroring evaluationSummary in the LEGACY events.ts.
function summaryLine(evaluation: Evaluation): string {
  if (!evaluation.signal) return `Discerned: ${evaluation.category}`;
  const rank = (SIGNAL_LEVELS as readonly string[]).indexOf(evaluation.signal) + 1;
  return `Discerned: ${'★'.repeat(rank)} ${evaluation.signal} — ${evaluation.category}`;
}

// Build a LEGACY Discerned kind:1 event template (pre-snippet format with a
// leading "Discerned: …" summary line). Old casts with this shape live forever
// on public relays; parseEvent must keep handling them.
function buildLegacyTemplate(capture: Capture, evaluation: Evaluation): EventTemplate {
  const tags: string[][] = [
    ['r', capture.url],
    ['L', 'online.discerned.category'],
    ['l', evaluation.category, 'online.discerned.category'],
  ];
  if (evaluation.signal) {
    tags.push(['L', 'online.discerned.signal']);
    tags.push(['l', evaluation.signal, 'online.discerned.signal']);
  }
  if (evaluation.qualifiers && evaluation.qualifiers.length > 0) {
    tags.push(['L', 'online.discerned.qualifier']);
    for (const q of evaluation.qualifiers) tags.push(['l', q, 'online.discerned.qualifier']);
  }
  tags.push(['t', 'discerned'], ['format', capture.format], ['client', 'discerned']);

  if (capture.note && capture.note.trim().length > 0) {
    tags.push(['note', capture.note]);
  }

  let content: string;
  if (capture.format === 'selection') {
    const quoted = capture.selectionText ?? '';
    tags.push(['quote', quoted]);
    if (capture.selectionContext) tags.push(['context', capture.selectionContext]);
    content = [
      summaryLine(evaluation),
      `> "${quoted}"`,
      '',
      capture.url,
    ].join('\n');
  } else {
    if (capture.title && capture.title.trim().length > 0) tags.push(['title', capture.title]);
    if (capture.thumbnail) tags.push(['image', capture.thumbnail]);
    if (capture.bodyText) tags.push(['body', capture.bodyText]);
    content = [
      summaryLine(evaluation),
      '',
      capture.title,
      capture.url,
    ].join('\n');
  }
  if (capture.note && capture.note.trim().length > 0) {
    content = `${content}\n\n— ${capture.note}`;
  }

  return {
    kind: 1,
    created_at: Math.floor(capture.timestamp / 1000),
    tags,
    content,
  };
}

const CLIPS_ROOT = resolve(__dirname, '..', '..', 'tests', 'fixtures', 'clips');

interface ClipFixture {
  name: string;
  capture: Capture;
  evaluation: Evaluation;
}

const fixtures: ClipFixture[] = readdirSync(CLIPS_ROOT)
  .filter((f) => f.endsWith('.json'))
  .map((file) => {
    const data = JSON.parse(readFileSync(resolve(CLIPS_ROOT, file), 'utf8')) as
      { capture: Capture; evaluation: Evaluation };
    return { name: file, ...data };
  });

const SK = generateSecretKey();

describe('parseEvent (web) — legacy pre-snippet cast format', () => {
  for (const fx of fixtures) {
    it(`round-trips ${fx.name}`, () => {
      const ev = finalizeEvent(buildLegacyTemplate(fx.capture, fx.evaluation), SK);
      const clip = parseEvent(ev);

      expect(clip.capture.format).toBe(fx.capture.format);
      expect(clip.capture.url).toBe(fx.capture.url);
      expect(clip.evaluation.signal).toBe(fx.evaluation.signal);
      expect(clip.evaluation.qualifiers).toEqual(fx.evaluation.qualifiers ?? []);
      expect(clip.evaluation.category).toBe(fx.evaluation.category);

      if (fx.capture.format === 'selection') {
        expect(clip.capture.selectionText).toBe(fx.capture.selectionText);
        // Selection casts carry no title tag — parseEvent falls back to the URL.
        expect(clip.capture.title).toBe(fx.capture.url);
        if (fx.capture.selectionContext) {
          expect(clip.capture.selectionContext).toBe(fx.capture.selectionContext);
        }
      } else {
        // Resource casts emit an explicit `title` tag that round-trips exactly.
        expect(clip.capture.title).toBe(fx.capture.title);
        if (fx.capture.bodyText) expect(clip.capture.bodyText).toBe(fx.capture.bodyText);
        if (fx.capture.thumbnail) expect(clip.capture.thumbnail).toBe(fx.capture.thumbnail);
      }

      if (fx.capture.note) expect(clip.capture.note).toBe(fx.capture.note);
      expect(clip.capture.authorPubkey).toBe(ev.pubkey);
      expect(clip.capture.title).not.toMatch(/^Discerned:/);
      expect(clip.capture.timestamp).toBe(ev.created_at * 1000);
    });
  }

  it('extracts image URLs from NIP-92 imeta tags', () => {
    const photos = [
      'https://pbs.twimg.com/media/AAA?format=webp&name=medium',
      'https://pbs.twimg.com/media/BBB?format=webp&name=medium',
    ];
    const ev = finalizeEvent({
      kind: 1,
      created_at: 1_700_000_000,
      tags: [
        ['r', 'https://x.com/CIA/status/123'],
        ['format', 'article'],
        ['image', photos[0]],
        ['imeta', `url ${photos[0]}`, 'm image/webp'],
        ['imeta', `url ${photos[1]}`],
      ],
      content: 'Discerned: General\n\nCIA on X\nhttps://x.com/CIA/status/123',
    }, SK);

    const clip = parseEvent(ev);
    expect(clip.capture.imageUrls).toEqual(photos);
    // The single `image` tag still populates thumbnail for legacy renderers.
    expect(clip.capture.thumbnail).toBe(photos[0]);
  });

  it('leaves imageUrls undefined when there are no imeta tags', () => {
    const ev = finalizeEvent({
      kind: 1,
      created_at: 1_700_000_000,
      tags: [['r', 'https://example.com'], ['format', 'article']],
      content: 'Discerned: General\n\nTitle\nhttps://example.com',
    }, SK);
    expect(parseEvent(ev).capture.imageUrls).toBeUndefined();
  });

  it('falls back to safe defaults when tags are missing', () => {
    const ev = finalizeEvent({
      kind: 1,
      created_at: 1_700_000_000,
      tags: [],
      content: 'A bare event\nwith just a title and a body',
    }, SK);

    const clip = parseEvent(ev);
    expect(clip.capture.url).toBe('');
    expect(clip.capture.format).toBe('bookmark');
    expect(clip.evaluation.signal).toBeUndefined();
    expect(clip.evaluation.qualifiers).toEqual([]);
    expect(clip.evaluation.category).toBe('General');
  });

  it('ignores an unrecognized signal level', () => {
    const ev = finalizeEvent({
      kind: 1,
      created_at: 1_700_000_000,
      tags: [
        ['L', 'online.discerned.signal'],
        ['l', 'Stupendous', 'online.discerned.signal'],
        ['L', 'online.discerned.category'],
        ['l', 'General', 'online.discerned.category'],
      ],
      content: 'x',
    }, SK);

    const clip = parseEvent(ev);
    expect(clip.evaluation.signal).toBeUndefined();
    expect(clip.evaluation.category).toBe('General');
  });
});

// ─── CURRENT cast format — templates generated by the real extension factory ──

const EVENTS_ROOT = resolve(__dirname, '..', '..', 'tests', 'fixtures', 'events');

interface GeneratedEventFixture {
  source: string;
  variant: 'kind1' | 'kind1-longform-ref' | 'kind30023';
  capture: Capture;
  evaluation: Evaluation;
  longFormRef?: { coord: string; naddr: string; relay?: string };
  template: EventTemplate;
}

const generated: Array<{ name: string; fx: GeneratedEventFixture }> = readdirSync(EVENTS_ROOT)
  .filter((f) => f.endsWith('.json'))
  .map((file) => ({
    name: file,
    fx: JSON.parse(readFileSync(resolve(EVENTS_ROOT, file), 'utf8')) as GeneratedEventFixture,
  }));

// What the factory publishes as the `image` tag: the first http(s) URL among
// thumbnailUrl → thumbnail → imageUrls (never a data: URI).
function expectedImageTag(capture: Capture): string | undefined {
  return [capture.thumbnailUrl, capture.thumbnail, ...(capture.imageUrls ?? [])]
    .find((u): u is string => !!u && /^https?:/i.test(u));
}

describe('parseEvent (web) — current cast format (factory-generated templates)', () => {
  it('has generated fixtures to test (run `pnpm test` in discerned-ext to regenerate)', () => {
    expect(generated.length).toBeGreaterThanOrEqual(6);
  });

  for (const { name, fx } of generated) {
    it(`round-trips ${name}`, () => {
      const ev = finalizeEvent(fx.template, SK);
      const clip = parseEvent(ev);

      // Evaluation axes round-trip on every variant.
      expect(clip.evaluation.signal).toBe(fx.evaluation.signal);
      expect(clip.evaluation.qualifiers).toEqual(fx.evaluation.qualifiers ?? []);
      expect(clip.evaluation.category).toBe(fx.evaluation.category);
      expect(clip.capture.format).toBe(fx.capture.format);
      expect(clip.capture.url).toBe(fx.capture.url);
      expect(clip.capture.authorPubkey).toBe(ev.pubkey);
      // Second-resolution timestamp preserved (published_at for 30023).
      expect(clip.capture.timestamp).toBe(Math.floor(fx.capture.timestamp / 1000) * 1000);

      // The attribution snippet must never leak into parsed fields.
      for (const field of [clip.capture.title, clip.capture.bodyText, clip.capture.markdown]) {
        if (field) {
          expect(field).not.toContain('Discerned →');
          expect(field).not.toContain(SNIPPET_SENTINEL_OPEN);
        }
      }

      if (fx.capture.note) expect(clip.capture.note).toBe(fx.capture.note);

      if (fx.variant === 'kind30023') {
        expect(clip.capture.kind).toBe(30023);
        // The d tag is the stable clip id — the dedup join key.
        expect(clip.capture.longFormId).toBe(fx.capture.id);
        if (fx.capture.title) expect(clip.capture.title).toBe(fx.capture.title);
        // Markdown carries the body (leading duplicate title heading stripped
        // by the factory; snippet stripped by the parser).
        const body = (fx.capture.bodyText ?? fx.capture.selectionText ?? '').trim();
        if (body) expect(clip.capture.markdown ?? '').toContain(body.slice(0, 40));
        return;
      }

      expect(clip.capture.kind).toBe(1);

      if (fx.variant === 'kind1-longform-ref') {
        // The a-tag's <d> segment joins the note to its 30023 for feed dedup.
        expect(clip.capture.longFormId).toBe(fx.capture.id);
        // With a companion long-form there is no `body` tag — teaser only.
        expect(clip.capture.bodyText).toBeUndefined();
      } else {
        expect(clip.capture.longFormId).toBeUndefined();
      }

      if (fx.capture.format === 'selection') {
        expect(clip.capture.selectionText).toBe(fx.capture.selectionText ?? '');
        if (fx.capture.selectionContext) {
          expect(clip.capture.selectionContext).toBe(fx.capture.selectionContext);
        }
        // Selection casts carry no title tag — parseEvent falls back to the URL.
        expect(clip.capture.title).toBe(fx.capture.url);
      } else {
        // Resource casts emit an explicit `title` tag that round-trips exactly.
        if (fx.capture.title) expect(clip.capture.title).toBe(fx.capture.title);
        if (fx.variant === 'kind1' && fx.capture.bodyText?.trim()) {
          // The body tag is the inline body minus a leading line duplicating
          // the title — always a substring of the original.
          expect(clip.capture.bodyText).toBeTruthy();
          expect(fx.capture.bodyText).toContain(clip.capture.bodyText ?? '');
        }
      }

      const img = expectedImageTag(fx.capture);
      if (img) expect(clip.capture.thumbnail).toBe(img);
      else expect(clip.capture.thumbnail).toBeUndefined();

      const httpImgs = (fx.capture.imageUrls ?? []).filter((u) => /^https?:/i.test(u));
      if (httpImgs.length > 0) expect(clip.capture.imageUrls).toEqual(httpImgs);
      else expect(clip.capture.imageUrls).toBeUndefined();
    });
  }
});
