'use client';

// Download + install instructions for the Discerned Chrome extension.
// The extension is distributed as an unpacked zip (discerned-extension.zip lives in
// public/, regenerated by `pnpm pack:ext` in discerned-ext/) that users side-load via
// chrome://extensions → Load unpacked. Linked from the "Get the extension" CTA on /about.

import { useState } from 'react';
import Link from 'next/link';
import TopBar from '@/components/chrome/TopBar';
import SignInModal from '@/components/auth/SignInModal';
import { useNostrAuth } from '@/hooks/useNostrAuth';
import { useBridgeAuth } from '@/hooks/useBridgeAuth';

const ZIP_HREF = '/discerned-extension.zip';

const codeStyle: React.CSSProperties = {
  fontFamily: 'var(--mono)',
  fontSize: '0.86em',
  background: 'var(--paper-3)',
  padding: '1px 6px',
  borderRadius: 4,
  color: 'var(--ink)',
};

// Mono/pill styling like codeStyle, but coloured + underlined to read as a link.
const codeLinkStyle: React.CSSProperties = {
  ...codeStyle,
  color: 'var(--accent-ink)',
  textDecoration: 'underline',
  textUnderlineOffset: 2,
};

const linkStyle: React.CSSProperties = {
  color: 'var(--accent-ink)',
  textDecoration: 'underline',
  textUnderlineOffset: 2,
};

const steps: { title: string; body: React.ReactNode }[] = [
  {
    title: 'Download and unzip',
    body: (
      <>
        Download{' '}
        <a href={ZIP_HREF} download style={codeLinkStyle}>discerned-extension.zip</a>{' '}
        and unzip it to a folder you&apos;ll keep — Chrome loads the extension from that folder
        every time it starts, so don&apos;t delete it afterward.
      </>
    ),
  },
  {
    title: 'Open the extensions page',
    body: (
      <>
        In Chrome (or Brave, Edge, or any Chromium browser) go to{' '}
        <code style={codeStyle}>chrome://extensions</code> — type or paste that into the address
        bar and press Enter.
      </>
    ),
  },
  {
    title: 'Turn on Developer mode',
    body: (
      <>
        Flip the <strong>Developer mode</strong> toggle in the top-right corner of the extensions
        page. This is what lets you load an unpacked extension.
      </>
    ),
  },
  {
    title: 'Load unpacked',
    body: (
      <>
        Click <strong>Load unpacked</strong> and select the folder you unzipped in step 1 (the one
        containing <code style={codeStyle}>manifest.json</code>). Discerned will appear in your
        extensions list.
      </>
    ),
  },
  {
    title: 'Pin it and start clipping',
    body: (
      <>
        Click the puzzle-piece icon in the toolbar and pin Discerned so it&apos;s one click away.
        Select some text on any page, open the extension, and clip it. Your clips show up on{' '}
        <Link href="/clips" style={linkStyle}>My Clips</Link>.
      </>
    ),
  },
];

export default function GetExtensionPage() {
  const { auth, signInPubkey } = useNostrAuth();
  const { extensionPresent } = useBridgeAuth();
  const [signInOpen, setSignInOpen] = useState(false);

  return (
    <div style={{ height: '100%', overflow: 'auto', background: 'var(--paper)' }}>
      <TopBar
        auth={auth}
        onSignIn={() => setSignInOpen(true)}
        extensionPresent={extensionPresent}
      />

      <section style={{ maxWidth: 720, margin: '0 auto', padding: '56px 32px 40px' }}>
        <div style={{ fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--ink-3)', marginBottom: 14 }}>
          Get the extension
        </div>
        <h1 style={{ fontFamily: 'var(--serif)', fontSize: 40, fontWeight: 500, color: 'var(--ink)', margin: '0 0 16px', letterSpacing: '-0.02em', lineHeight: 1.1 }}>
          Install Discerned<br /><em style={{ fontStyle: 'italic', color: 'var(--accent-ink)' }}>in about a minute.</em>
        </h1>
        <p style={{ fontFamily: 'var(--serif)', fontSize: 17, color: 'var(--ink-2)', lineHeight: 1.65, margin: '0 0 28px' }}>
          Discerned isn&apos;t on the Chrome Web Store yet, so you install it directly from us. It&apos;s
          the same one-time process developers use — download the package, then load it into your
          browser.
        </p>

        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>
          <a href={ZIP_HREF} download className="btn primary" style={{ textDecoration: 'none', fontSize: 14, padding: '11px 18px' }}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 2 }}>
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            Download extension (.zip)
          </a>
          <span style={{ fontFamily: 'var(--mono)', fontSize: 11, color: 'var(--ink-3)' }}>
            Chrome · Brave · Edge · any Chromium browser
          </span>
        </div>
      </section>

      <section style={{ maxWidth: 720, margin: '0 auto', padding: '8px 32px 40px' }}>
        <h2 style={{ fontFamily: 'var(--serif)', fontSize: 24, fontWeight: 500, color: 'var(--ink)', margin: '0 0 24px', letterSpacing: '-0.015em' }}>
          How to install
        </h2>
        <ol style={{ listStyle: 'none', margin: 0, padding: 0, display: 'flex', flexDirection: 'column', gap: 20 }}>
          {steps.map((step, i) => (
            <li key={step.title} style={{ display: 'flex', gap: 16, alignItems: 'flex-start' }}>
              <span
                aria-hidden="true"
                style={{
                  flex: '0 0 auto', width: 30, height: 30, borderRadius: '50%',
                  border: '1px solid var(--rule)', background: 'var(--paper-2)',
                  display: 'grid', placeItems: 'center',
                  fontFamily: 'var(--mono)', fontSize: 13, fontWeight: 600, color: 'var(--ink-2)',
                  marginTop: 2,
                }}
              >
                {i + 1}
              </span>
              <div>
                <h3 style={{ fontFamily: 'var(--serif)', fontSize: 17, fontWeight: 600, color: 'var(--ink)', margin: '2px 0 6px' }}>
                  {step.title}
                </h3>
                <p style={{ fontFamily: 'var(--serif)', fontSize: 15, color: 'var(--ink-2)', lineHeight: 1.6, margin: 0 }}>
                  {step.body}
                </p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section style={{ maxWidth: 720, margin: '0 auto', padding: '8px 32px 80px' }}>
        <div style={{ border: '1px solid var(--rule)', borderRadius: 10, background: 'var(--paper-2)', padding: '20px 22px' }}>
          <h3 style={{ fontFamily: 'var(--serif)', fontSize: 16, fontWeight: 600, color: 'var(--ink)', margin: '0 0 8px' }}>
            Good to know
          </h3>
          <ul style={{ margin: 0, padding: '0 0 0 18px', fontFamily: 'var(--serif)', fontSize: 14.5, color: 'var(--ink-2)', lineHeight: 1.6 }}>
            <li style={{ marginBottom: 6 }}>
              Your clips are stored locally in your browser. Nothing is uploaded until you choose to cast it.
            </li>
            <li style={{ marginBottom: 6 }}>
              Chrome may show a &ldquo;Developer mode extensions&rdquo; reminder on startup — that&apos;s normal for unpacked extensions and safe to dismiss.
            </li>
            <li>
              Keep the unzipped folder where it is. If you move or delete it, remove and re-add the extension from that new location.
            </li>
          </ul>
          <p style={{ fontFamily: 'var(--serif)', fontSize: 14.5, color: 'var(--ink-2)', lineHeight: 1.6, margin: '16px 0 0' }}>
            Want the details? Read <Link href="/about" style={linkStyle}>what Discerned is and why it works this way →</Link>
          </p>
        </div>
      </section>

      {signInOpen && (
        <SignInModal
          onClose={() => setSignInOpen(false)}
          onSignedIn={(pubkey) => signInPubkey(pubkey)}
        />
      )}
    </div>
  );
}
