// Generates cross-package event-template fixtures from the REAL event factory.
//
// The web app's parse tests used to hand-mirror the extension's event format —
// which silently drifted when the format changed (the "Discerned: …" summary
// line era). Instead, this test builds an EventTemplate for every clip fixture
// via the actual factory functions and writes them (write-if-changed) to
// tests/fixtures/events/*.json at the monorepo root. discerned-web's
// parse.test.ts signs and parses those templates, so any factory change is
// exercised against the real parser on the next `pnpm test`.
//
// The files are committed to git: regenerate by running this suite
// (`pnpm test` in discerned-ext), then commit the diff alongside the factory
// change. Templates are deterministic (no signatures — the web side signs with
// its own throwaway key), so unchanged factories produce zero churn.

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, basename } from 'node:path';
import {
  createQuoteNoteEvent,
  createResourceNoteEvent,
  createLongFormEvent,
  buildDiscernedSnippet,
  type LongFormRef,
} from '@/shared/nostr/events';
import type { Capture, Evaluation } from '@/shared/types';
import type { EventTemplate } from 'nostr-tools/core';

const CLIPS_ROOT = resolve(__dirname, '..', '..', '..', 'tests', 'fixtures', 'clips');
const EVENTS_ROOT = resolve(__dirname, '..', '..', '..', 'tests', 'fixtures', 'events');

// Placeholder pubkey inside the 'a'-tag coordinate. The web test only checks
// that the <d> segment round-trips; the pubkey segment is never validated.
const REF_PUBKEY = 'f'.repeat(64);

interface GeneratedEventFixture {
  $comment: string;
  source: string;
  variant: 'kind1' | 'kind1-longform-ref' | 'kind30023';
  capture: Capture;
  evaluation: Evaluation;
  longFormRef?: LongFormRef;
  template: EventTemplate;
}

function loadClips(): Array<{ name: string; capture: Capture; evaluation: Evaluation }> {
  return readdirSync(CLIPS_ROOT)
    .filter((f) => f.endsWith('.json'))
    .map((file) => {
      const data = JSON.parse(readFileSync(resolve(CLIPS_ROOT, file), 'utf8')) as
        { capture: Capture; evaluation: Evaluation };
      return { name: basename(file, '.json'), ...data };
    });
}

function buildFixtures(): GeneratedEventFixture[] {
  const out: GeneratedEventFixture[] = [];
  const comment =
    'GENERATED by discerned-ext/tests/nostr/event-fixture-generation.test.ts — do not edit by hand.';

  for (const { name, capture, evaluation } of loadClips()) {
    const snippet = buildDiscernedSnippet(evaluation);

    // Plain kind-1 cast — the shape handleCast publishes when no long-form
    // companion exists.
    const kind1 =
      capture.format === 'selection'
        ? createQuoteNoteEvent(capture, evaluation, snippet)
        : createResourceNoteEvent(capture, evaluation, capture.bodyText, snippet);
    out.push({ $comment: comment, source: `${name}.json`, variant: 'kind1', capture, evaluation, template: kind1 });

    // Rich formats also publish a kind-30023 companion + a summary-and-link
    // kind-1 that references it. Emit both variants for those.
    if (capture.format === 'article' || capture.format === 'full-page' || capture.format === 'selection') {
      const ref: LongFormRef = {
        coord: `30023:${REF_PUBKEY}:${capture.id}`,
        naddr: 'naddr1generatedfixtureexample',
        relay: 'wss://relay.example.com',
      };
      const kind1Ref =
        capture.format === 'selection'
          ? createQuoteNoteEvent(capture, evaluation, snippet, ref)
          : createResourceNoteEvent(capture, evaluation, capture.bodyText, snippet, ref);
      out.push({
        $comment: comment, source: `${name}.json`, variant: 'kind1-longform-ref',
        capture, evaluation, longFormRef: ref, template: kind1Ref,
      });

      // Long-form markdown body: the real pipeline converts bodyHtml via
      // turndown; clip fixtures carry plain text, which is valid markdown.
      const markdown = `# ${capture.title}\n\n${capture.bodyText ?? capture.selectionText ?? 'Body.'}`;
      out.push({
        $comment: comment, source: `${name}.json`, variant: 'kind30023',
        capture, evaluation,
        template: createLongFormEvent(capture, evaluation, markdown, snippet),
      });
    }
  }
  return out;
}

describe('event-template fixture generation (cross-package contract)', () => {
  it('writes one template per clip fixture + long-form variants', () => {
    const fixtures = buildFixtures();
    expect(fixtures.length).toBeGreaterThanOrEqual(6);
    mkdirSync(EVENTS_ROOT, { recursive: true });

    let written = 0;
    for (const fx of fixtures) {
      const file = resolve(EVENTS_ROOT, `${fx.source.replace(/\.json$/, '')}.${fx.variant}.json`);
      const next = JSON.stringify(fx, null, 2) + '\n';
      const prev = existsSync(file) ? readFileSync(file, 'utf8') : null;
      if (prev !== next) {
        writeFileSync(file, next, 'utf8');
        written++;
      }
    }
    // Informational only — a change here means the factory output changed and
    // the regenerated fixtures should be committed with it.
    // eslint-disable-next-line no-console
    if (written > 0) console.log(`[event-fixtures] regenerated ${written}/${fixtures.length} template fixture(s) in tests/fixtures/events/`);

    // Every template must be a valid unsigned event shape.
    for (const fx of fixtures) {
      expect(fx.template.kind === 1 || fx.template.kind === 30023).toBe(true);
      expect(fx.template.created_at).toBe(Math.floor(fx.capture.timestamp / 1000));
      expect(Array.isArray(fx.template.tags)).toBe(true);
      expect(typeof fx.template.content).toBe('string');
    }
  });
});
